### ISSUE TITLE
Rotate 180deg VRM sample around Y

### ISSUE THREAD

**Issue by ku6ryo** [styly-dev/STYLY-visionOS-Plugin#116]
The girl avatar stands with her back to users.

**Comment by DglyP** [comment]
![Image](https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/cb4a54ab-2e1f-4ef1-9388-7c0ec04439de)

Updated the nodes to include a rotation tool, this enables us to edit the rotation of the model after we receive it from the URL. The implementation has to be discussed during a following meeting.



![Image](https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/5ac9f6df-f457-4d78-a29b-1defc2eba585)

**Comment by from2001** [comment]
@DglyP I am confused.  What is the expected behaviour of the node?

If a VRM model appears with wrong direction, we better just fix the rotation of the model.

>this enables us to edit the rotation of the model after we receive it from the URL

What does the `Rotate On Y Axis` do?

**Comment by from2001** [comment]
I think I understand now.
What you want to do is moving the VRM avatar after it appears. (Not just for Y rotation)

I tried to do it using the output Game Object, but it didn't work. I think what we should fix is to fix is the output GameObject.

<img width="1748" alt="Screenshot 2024-07-01 at 12 44 30" src="https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/387880/967586d7-a08c-46d6-8438-02a25119fade">

**Comment by DglyP** [comment]
Ah I understand what you want to do now. As per @ku6ryo discussion, I fixed the sample so that the character is not looking opposite to the direction of the camera. 

I understand what you want now, you want to make it so that the output of the node is the VRM itself, or a GameObject containing the VRM. After that you can just use any node to transform or rotate it. 

I'll perform the change.

**Comment by from2001** [comment]
Great. Thanks.

I just want to let you know that VRM samples can also be imported from the package. 

<img width="1107" alt="Screenshot 2024-07-01 at 17 52 54" src="https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/387880/a5ef645d-b3ba-4dbb-ae02-16360e89eeda">

**Comment by DglyP** [comment]
After analyzing a little bit more and doing some research on the matter, it seems that this is not a bug and that the implementation is correct. If we add the nodes as follows, it changes the rotation of the VRM as we want it. 

<img width="876" alt="image" src="https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/643d1907-69b5-45cb-9d39-b04f8882bbfb">

The reason why this took a while to check is because of the misunderstanding of how the implementation was done. Also, sometimes the models are facing Z-forwards or Z-backwards, which makes it difficult to make sure that they are always facing the user. 

At this point, using the nodes proposed is the best option. No changes required.
