### ISSUE TITLE
Rotate 180deg online model sample around Y

### ISSUE THREAD

**Issue by ku6ryo** [styly-dev/STYLY-visionOS-Plugin#117]
The model stands with its back to users.

**Comment by DglyP** [comment]
![Image](https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/fc139742-213a-476d-b019-8c4a6291bfdf)

Decided to include a different edition tool in the nodes here. Due to the fact that GLTF objects sometimes have rotation issues (where the axis can be flipped), I decided to include a Vector3 implementation that enables the users to rotate on every axis after the import. A target object is not required for this step but it might be recommended if this is the way that we want to implement the fix. We may discuss this during the next meeting.


![Image](https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/c0b22643-63bb-4358-a6ac-d4801a0c37fb)

**Comment by DglyP** [comment]
Following with the analysis of the nodes on the 180 rotation of the VRM package, we notice that the issue is the same. The way that the nodes were connected is not correct. By using the following implementation of the nodes, we can achieve the required rotation without needing to change the code itself.

<img width="827" alt="image" src="https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/assets/23158852/a6aef40d-93a0-4beb-8488-f38a71dc67a8">
